#Made by BGHDNetwork(Noodles)
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/46407
#=======================================================
Update:
  Enabled: true
#noweather.update
#Enables if there is a message on-join when the plugin is outdated. 
#=======================================================
